### Word Embedding Techniques using Embedding Layer in Keras

In [1]:
##tensorflow >2.0
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
### Vocabulary size
voc_size=10000

#### One Hot Representation

In [5]:
onehot_repr=[one_hot(words,voc_size)for words in sent] 
print(onehot_repr)

[[9180, 6630, 7251, 100], [9180, 6630, 7251, 9550], [9180, 6944, 7251, 8511], [8380, 2904, 7245, 2092, 1679], [8380, 2904, 7245, 2092, 9315], [633, 9180, 8708, 7251, 771], [6841, 926, 6993, 2092]]


### Word Embedding Represntation

In [6]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [7]:
import numpy as np

In [8]:
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 9180 6630 7251  100]
 [   0    0    0    0 9180 6630 7251 9550]
 [   0    0    0    0 9180 6944 7251 8511]
 [   0    0    0 8380 2904 7245 2092 1679]
 [   0    0    0 8380 2904 7245 2092 9315]
 [   0    0    0  633 9180 8708 7251  771]
 [   0    0    0    0 6841  926 6993 2092]]


In [9]:
dim=10


In [10]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [11]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [12]:
print(model.predict(embedded_docs))

1/1 [==============================] - 3s 3s/step
[[[-2.30194926e-02  4.23038490e-02 -1.89562570e-02 -2.07310803e-02
    2.82571800e-02  3.48467119e-02 -2.92740222e-02  1.14592537e-02
   -2.42428314e-02 -4.95991372e-02]
  [-2.30194926e-02  4.23038490e-02 -1.89562570e-02 -2.07310803e-02
    2.82571800e-02  3.48467119e-02 -2.92740222e-02  1.14592537e-02
   -2.42428314e-02 -4.95991372e-02]
  [-2.30194926e-02  4.23038490e-02 -1.89562570e-02 -2.07310803e-02
    2.82571800e-02  3.48467119e-02 -2.92740222e-02  1.14592537e-02
   -2.42428314e-02 -4.95991372e-02]
  [-2.30194926e-02  4.23038490e-02 -1.89562570e-02 -2.07310803e-02
    2.82571800e-02  3.48467119e-02 -2.92740222e-02  1.14592537e-02
   -2.42428314e-02 -4.95991372e-02]
  [ 7.27988407e-03  4.31966297e-02  1.13495439e-03 -3.69513407e-02
   -1.47994868e-02  4.23896573e-02  4.06865515e-02  2.46018432e-02
    3.07904556e-03  3.47711705e-02]
  [ 2.76035406e-02  4.57626469e-02 -1.20944604e-02 -1.32949241e-02
   -4.45121527e-02 -2.31692679e-0

In [13]:
embedded_docs[0]

array([   0,    0,    0,    0, 9180, 6630, 7251,  100])

In [14]:
print(model.predict(embedded_docs)[0])

1/1 [==============================] - 0s 22ms/step
[[-0.02301949  0.04230385 -0.01895626 -0.02073108  0.02825718  0.03484671
  -0.02927402  0.01145925 -0.02424283 -0.04959914]
 [-0.02301949  0.04230385 -0.01895626 -0.02073108  0.02825718  0.03484671
  -0.02927402  0.01145925 -0.02424283 -0.04959914]
 [-0.02301949  0.04230385 -0.01895626 -0.02073108  0.02825718  0.03484671
  -0.02927402  0.01145925 -0.02424283 -0.04959914]
 [-0.02301949  0.04230385 -0.01895626 -0.02073108  0.02825718  0.03484671
  -0.02927402  0.01145925 -0.02424283 -0.04959914]
 [ 0.00727988  0.04319663  0.00113495 -0.03695134 -0.01479949  0.04238966
   0.04068655  0.02460184  0.00307905  0.03477117]
 [ 0.02760354  0.04576265 -0.01209446 -0.01329492 -0.04451215 -0.02316927
  -0.03347524 -0.01660307  0.04373923  0.04839778]
 [ 0.03051451  0.00977993  0.03490267 -0.00027265 -0.04732043  0.03897704
  -0.03580637 -0.00899117  0.00357702  0.03107188]
 [ 0.03653573  0.03108188 -0.01832327 -0.02605534  0.02544974 -0.04366232